# Generated by Django 4.0.2 on 2022-06-12 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cybersport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='slug',
            field=models.CharField(max_length=300),
        ),
    ]
