# Generated by Django 4.0.2 on 2022-06-12 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cybersport', '0002_alter_new_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='new',
            name='image_url',
            field=models.CharField(default=None, max_length=300, null=True),
        ),
    ]
