# Generated by Django 4.0.2 on 2022-09-04 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Cybersport', '0002_alter_newcomment_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewComment',
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_object_type', models.CharField(choices=[('N', 'New'), ('U', 'User')], max_length=1)),
                ('text', models.CharField(max_length=5000)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('new', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Cybersport.new')),
                ('rating', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_comment', to='Cybersport.rating')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'comment',
            },
        ),
    ]
