# Generated by Django 4.0.2 on 2022-09-04 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cybersport', '0003_comment_delete_newcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='new',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='related_object_type',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AlterField(
            model_name='new',
            name='slug',
            field=models.SlugField(max_length=300),
        ),
    ]
