# Generated by Django 4.0.2 on 2022-06-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cybersport', '0003_alter_category_options_alter_new_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='image_url',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
