# Generated by Django 4.0.2 on 2022-09-04 20:44

import Cybersport.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cybersport', '0005_comment_content_type_comment_object_id'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', Cybersport.models.CustomUserManager()),
            ],
        ),
    ]
