# Generated by Django 4.0.2 on 2022-07-04 17:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Cybersport', '0006_alter_category_options_alter_new_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 4, 17, 46, 28, 709285, tzinfo=utc)),
        ),
    ]
