# Generated by Django 4.0.2 on 2022-07-04 17:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Cybersport', '0008_alter_new_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
