# Generated by Django 4.0.2 on 2022-07-26 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cybersport', '0011_alter_new_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(default='', max_length=100, verbose_name='Slug'),
        ),
    ]
