# Generated by Django 4.0.2 on 2022-08-15 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Cybersport', '0013_alter_category_name_alter_category_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=5000)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('new', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cybersport.new')),
            ],
            options={
                'db_table': 'comment',
            },
        ),
    ]
