# Generated by Django 4.0.2 on 2022-08-17 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cybersport', '0015_like_dislike'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dislikes', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='rating', to='Cybersport.dislike')),
                ('likes', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='rating', to='Cybersport.like')),
            ],
        ),
    ]
