# Generated by Django 4.0.2 on 2022-08-17 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cybersport', '0016_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='rating',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_object', to='Cybersport.rating'),
        ),
    ]
