# Generated by Django 4.0.2 on 2022-08-17 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cybersport', '0017_new_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='likes',
        ),
        migrations.AddField(
            model_name='rating',
            name='text',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.DeleteModel(
            name='Dislike',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
