# Generated by Django 4.0.2 on 2022-08-17 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cybersport', '0018_remove_like_user_remove_rating_dislikes_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rating',
            table='rating',
        ),
    ]
