# Generated by Django 4.0.2 on 2022-08-19 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Cybersport', '0021_alter_dislike_rating_alter_dislike_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dislike',
            name='rating',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dislikes', to='Cybersport.rating'),
        ),
        migrations.AlterField(
            model_name='dislike',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='like',
            name='rating',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='Cybersport.rating'),
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
